# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('cause', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=150)),
                ('name_of_place_opt', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=240)),
            ],
        ),
    ]
