# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170802_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
