# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_date_and_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name_of_place_opt',
            new_name='name_of_place',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_date_and_time',
        ),
    ]
