# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170803_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
