# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 05:50
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/pi/djcode/xpcpro/xpcpro/images'), upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='event',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
