# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170806_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=events.models.upload_location, width_field='width_field'),
        ),
    ]
