# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170807_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=events.models.upload_location),
        ),
    ]
