# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170807_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='event',
            name='width_field',
        ),
    ]
