# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170807_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='town',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='us_state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='z_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
