# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20170807_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, default='catalyzeLogo.png', null=True, upload_to=events.models.upload_location),
        ),
    ]
