# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20170807_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='town',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='us_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='z_code',
            new_name='zip_code',
        ),
    ]
