# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20170807_1340'),
        ('events', '0012_auto_20170807_1338'),
    ]

    operations = [
    ]
