# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20170808_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date_and_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_and_time',
            field=models.CharField(max_length=50),
        ),
    ]
